### ISSUE TITLE
在 Linux 容器环境下无法连接服务器

### ISSUE THREAD

**Issue by eltonfan** [Yancy1028/Jusoft.DingtalkStream#1]
**现象**
在 Linux 容器环境中，`GetLocalIps` 会出现异常，导致无法连接服务器。

**建议**
钉钉 Stream 协议中的 `localIp` 为可选参数，也许 `try...catch` ，不行就留空？

**详细日志**
```
13:36:55.685  +3,809µs [INF] [15,106,840   +8,152B]  7 Jusoft.DingtalkStream.Core.DingtalkStreamClient| 开始请求钉钉访问网关及凭据。
13:36:55.700 +14,991µs [ERR] [15,229,688 +122,848B]  7 Jusoft.DingtalkStream.Core.DingtalkStreamClient| 建立 WebSocket 连接时发生了异常。
System.PlatformNotSupportedException: The information requested is unavailable on the current platform.
   at System.Net.NetworkInformation.UnixUnicastIPAddressInformation.get_DuplicateAddressDetectionState()
   at Jusoft.DingtalkStream.Core.Internals.Utilities.GetLocalIps()+MoveNext()
   at System.String.JoinCore[T](ReadOnlySpan`1 separator, IEnumerable`1 values)
   at System.String.Join[T](Char separator, IEnumerable`1 values)
   at Jusoft.DingtalkStream.Core.DingtalkStreamClient.GetGatewayEndPoint()
   at Jusoft.DingtalkStream.Core.DingtalkStreamClient.Start()
13:36:55.705  +5,484µs [INF] [15,287,032  +57,344B]  7 Jusoft.DingtalkStream.Core.DingtalkStreamClient| 尝试第1次重连。
13:36:55.706    +596µs [ERR] [15,295,224   +8,192B]  7 Jusoft.DingtalkStream.Core.Internals.DingtalkStreamClientWorker| 订阅程序已停止运行。
System.NullReferenceException: Object reference not set to an instance of an object.
   at Jusoft.DingtalkStream.Core.DingtalkStreamClient.Start()
   at Jusoft.DingtalkStream.Core.Internals.DingtalkStreamClientWorker.ExecuteAsync(CancellationToken stoppingToken)
```

**相关链接**
[ Stream模式协议接入说明 ](https://open.dingtalk.com/document/direction/stream-mode-protocol-access-description)
```
# POST /v1.0/gateway/connections/open

localIp | String | 否 | 运行SDK服务的当前本地IP，方便定位排查连接问题
```

**Comment by Yancy1028** [comment]
莫慌~~当时考虑的方便排查问题，避免自己去操作获取IP，这里我排查调整下
感谢兄弟指出问题~

**Comment by eltonfan** [comment]
收到。坐等新版本。不需要自己拉 pr 和发包，太美好了

**Comment by Yancy1028** [comment]
> 收到。坐等新版本。不需要自己拉 pr 和发包，太美好了

包已发布。
版本号：0.1.4
后续有其他问题可以继续反馈，代码写的比较糙，还需要大家多反馈问题来完善。><
